### ISSUE TITLE
Naive datetime

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#31] opened 2014-03-13 20:24 UTC
While running tests and the testserver the following warning keeps occuring:

/usr/local/lib/python3.3/dist-packages/django/db/models/fields/**init**.py:903: RuntimeWarning: DateTimeField Review.timestamp received a naive datetime (2014-03-06 20:23:04.259617) while time zone support is active.
  RuntimeWarning)

**Comment by martijnbastiaan** [comment] 2014-03-13 20:36
This is a duplicate of issue #18.

**Closed as completed** 2014-03-17 13:35 UTC
Labels: bug, duplicate
